name: pitchupdart
description: This library can be used to implement your own instrument tuning app.
version: 0.0.3
homepage: https://techpotatoes.github.io/pitchup_dart/

environment:
  sdk: '>=3.3.1 <4.0.0'

dev_dependencies:
  test: ^1.25.2